const styles = {
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(12, 9, 10, 0.8)",
  },
  logo: {
    width: "30%",
    height: "15%",
    marginBottom: 30,
    backgroundColor: "black",
  },
  backIconContainer: {
    position: "absolute",
    top: 50,
    left: 20,
    zIndex: 1,
  },
  loginTitle: {
    fontFamily: "Font-Bold",
    fontSize: 30,
    color: "#fff",
    marginBottom: 10,
    textAlign: "center",
  },
  topicon: {
    fontFamily: "Font-Bold",
    fontSize: 30,
    color: "#90EE90",
  },
  titlepart: {
    marginBottom: 30,
  },
  loginSubTitle: {
    fontFamily: "Font-Bold",
    fontSize: 15,
    color: "rgba(255, 255, 255, 0.6)",
    marginBottom: 30,
    width: 350,
    letterSpacing: 0.18,
    textAlign: "center",
  },
  inputContainer: {
    width: 350,
    marginBottom: 10,
  },
  label: {
    fontFamily: "Font-Bold",
    fontSize: 16,
    marginBottom: 5,
    color: "white",
  },
  input: {
    width: "100%",
    height: 40,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: "gray",
    borderRadius: 5,
    color: "#fff",
    fontSize: 17,
  },
  loginButton: {
    marginTop: 10,
    width: 200,
    height: 50,
    borderRadius: 25,
    backgroundColor: "#fff",
    justifyContent: "center",
    borderBottomColor: "#90EE90",
    borderLeftColor: "skyblue",
    borderRightColor: "skyblue",
    borderBottomWidth: 3,
    borderLeftWidth: 3,
    borderRightWidth: 3,
    alignItems: "center",
  },
  loginButtonText: {
    fontFamily: "Font-Bold",
    fontSize: 20,
    alignItems: "center",
    fontWeight: "500",
    color: "#000",
  },
  registerButton: {
    marginTop: 20,
    width: 200,
    height: 50,
    borderRadius: 25,
    backgroundColor: "rgba(255, 255, 255, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  alternateText: {
    color: "grey",
    fontFamily: "Font-Bold",
    fontSize: 13,
    marginTop: 15,
  },
  span: {
    color: "#90EE90",
    fontSize: 15,
  },
  iconContainer: {
    marginRight: 10,
  },
  icon: {
    color: "white",
  },
  forgotPasswordButton: {
    alignSelf: "center",
    marginTop: 10,
  },
  forgotPasswordText: {
    color: "white",
    textDecorationLine: "underline",
  },
};

export default styles;
