const styles = {
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(12, 9, 10, 0.8)",
  },
  logo: {
    width: "50%",
    height: "15%",
    backgroundColor: "transparent",
  },
  backIconContainer: {
    position: "absolute",
    top: 50,
    left: 20,
    zIndex: 1,
  },
  loginTitle: {
    fontFamily: "Font-Bolds",
    fontSize: 25,
    color: "#fff",
    fontWeight: "bold",
    marginBottom: 15,
    textAlign: "center",
  },
  titlepart: {
    marginBottom: 30,
  },
  loginSubTitle: {
    fontFamily: "Font-Bolds",
    fontSize: 15,
    color: "rgba(255, 255, 255, 0.8)",
    marginBottom: 30,
    width: 350,
    letterSpacing: 0.18,
    textAlign: "center",
  },
  label: {
    fontFamily: "Font-Bolds",
    fontSize: 16,
    marginBottom: 5,
    color: "white",
  },
  input: {
    width: "100%",
    height: 40,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: "gray",
    borderRadius: 5,
    color: "#fff",
    fontSize: 17,
  },
  inputContainer: {
    width: 350,
    marginBottom: 10,
    justifyContent: "center",
    textAlign: "center",
  },
  registerButton: {
    marginTop: 20,
    width: 200,
    height: 50,
    borderRadius: 25,
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    justifyContent: "center",
    borderBottomColor: "#90EE90",
    borderLeftColor: "skyblue",
    borderRightColor: "skyblue",
    borderBottomWidth: 3,
    borderLeftWidth: 3,
    borderRightWidth: 3,
    alignItems: "center",
  },
  registerLink: {
    fontFamily: "Font-Bolds",
    fontSize: 21,
    alignItems: "center",
    fontWeight: "bold",
    color: "black",
  },
  alternateText: {
    color: "grey",
    fontFamily: "Font-Bolds",
    fontSize: 13,
    marginTop: 15,
  },
  span: {
    color: "#90EE90",
    fontSize: 16,
  },
};

export default styles;
